services:
  - type: web
    name: your-service-name
    env: node
    buildCommand: "npm install && npx playwright install --with-deps"
    startCommand: "npm start"
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    port: 8080  # Đảm bảo port này tương thích với ứng dụng của bạn
